stages:
  - build
  - test

variables:
  GO_IMAGE: "golang:1.19-alpine"

before_script:
  - apk add --no-cache git build-base

build:
  stage: build
  image: $GO_IMAGE
  script:
    - cd $CI_PROJECT_DIR/src
    - go mod tidy
    - go build -o main .

test:
  stage: test
  image: $GO_IMAGE
  script:
    - cd $CI_PROJECT_DIR/src
    - go test -v ./...
