stages:
  - build
  - test

variables:
  GO_IMAGE: "golang:1.19-alpine"

before_script:
  - mkdir -p /app
  - cd /app

build:
  stage: build
  image: $GO_IMAGE
  script:
    - apk add --no-cache git
    - cd src
    - go mod tidy
    - go build -o main .

test:
  stage: test
  image: $GO_IMAGE
  script:
    - apk add --no-cache git
    - cd src
    - go test -v ./...
